### ISSUE TITLE
plugin doesn't work on 1.12.2 still.

### ISSUE THREAD

**Issue by SladeHazard** [GC-spigot/battle-pass#332]
### Describe the bug

Error when you click the quest week items in /battlepass gui aand it doesn't open

 [06:52:39 ERROR]: Could not pass event InventoryClickEvent to BattlePass v3.16.8
java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.setCustomModelData(Ljava/lang/Integer;)V
        at me.hyfe.simplespigot.item.SpigotItem$Builder.createMeta(SpigotItem.java:581) ~[?:?]
        at me.hyfe.simplespigot.item.SpigotItem$Builder.build(SpigotItem.java:546) ~[?:?]
        at me.hyfe.simplespigot.item.SpigotItem$Builder.build(SpigotItem.java:523) ~[?:?]
        at io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:60) ~[?:?]
        at io.github.battlepass.menus.menus.WeekMenu.pageableItem(WeekMenu.java:27) ~[?:?]
        at me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:67) ~[?:?]
        at io.github.battlepass.menus.menus.WeekMenu.redraw(WeekMenu.java:89) ~[?:?]
        at me.hyfe.simplespigot.menu.Menu.show(Menu.java:62) ~[?:?]
        at io.github.battlepass.menus.menus.QuestOverviewMenu.lambda$pageableItem$4(QuestOverviewMenu.java:68) ~[?:?]
        at me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:36) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1611.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(:70) ~[server.jar:git-Paper-2116373]
        at co.aikar.timings.TimedEventExecutor.execute(:74) ~[server.jar:git-Paper-2116373]
        at org.bukkit.plugin.RegisteredListener.callEvent(:62) ~[server.jar:git-Paper-2116373]
        at org.bukkit.plugin.SimplePluginManager.callEvent(:513) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(:2014) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(:23) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(:10) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(:14) ~[server.jar:git-Paper-2116373]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(:46) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(:854) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(:431) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778) ~[server.jar:git-Paper-2116373]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669) ~[server.jar:git-Paper-2116373]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]

### How to reproduce

type /bp
and go to quests and click any quest category

### Screenshots / Videos

server version 1.12.2

### Server Log

N/A

**Comment by GC-spigot** [comment]
Sorry about this! Fixed
