### ISSUE TITLE
1.8 | 1.9 | 1.10 | 1.11 | 1.12 | 1.13 | 1.14 Issue w/ Battlepass Quests & Plugin onEnable

### ISSUE THREAD

**Issue by ItzFabb-uwu** [GC-spigot/battle-pass#454]
### Describe the bug

**(1.8 all the way to 1.14.4 Issue with HARVEST-CROPS type of quest)**
 The bug can be re-produce from using the following configuration format
 ```
 quests:
  1:
    type: harvest-crops
    variable:
      root: CROPS:7 #CROPS > WHEATS on 1.8 - 1.12 !
    name: 'Weekly Quest | Harvest Wheat (x64)'
    required-progress: '64'
    points: 25
    item:
      material: WHEAT:0
      name: '&eHarvest x64 Wheats'
      lore:
      - ''
      - '&e▎&7In order to complete the quest, you must'
      - '&e▎&7harvest &fx64 Wheats&7.'
      - ''
      - '&e▎ &7Wheats: &6x%total_progress%&8/&ex64 Wheats'
      - '&e▎ &8( &c%progress_bar%&8 )&6 %percentage_progress%'
      - ''
      - '&eRewards'
      - '&e▎ &f+25 Points'
      - ''
  ```

  **(1.8 all the way to 1.14.4 Issue with CRAFT ( BLOCK MATERIAL) type of quest)**
  The bug can be re-produce from using the following configuration format
  ```
 quests:
  1:
    type: craft
    variable: TNT:0
    name: 'Weekly Quest | Craft a TNTs (x16)'
    required-progress: '16'
    points: 75
    item:
      material: TNT:0
      name: '&eCraft x16 TNTs'
      lore:
      - ''
      - '&e▎&7In order to complete the quest, you must'
      - '&e▎&7h7craft &fx16 TNTs&7.'
      - ''
      - '&e▎ &7TNTs: &6x%total_progress%&8/&ex16 TNTs'
      - '&e▎ &8( &c%progress_bar%&8 )&6 %percentage_progress%'
      - ''
      - '&eRewards'
      - '&e▎ &f+75 Points'
      - ''
  ```
Battlepass Version 4.0.18 ( Latest ) is also having an issue related to EntityBreedQuests
this error is occur by using the default config after you've /bpa reload or reloaded the plugin, there will be a message nor a warning information pop up on the console.

Battlepass Version 4.0.18 is also does not work on the minecraft 1.14.4!
Yeah about this idk why but it just doesn't work !
```
[00:52:09 ERROR]: Error occurred while enabling BattlePass v4.0.18 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/lang3/tuple/ImmutablePair
        at net.advancedplugins.bp.impl.actions.objects.variable.Variable.parseRoots(Variable.java:51) ~[?:?]
        at net.advancedplugins.bp.impl.actions.objects.variable.Variable.<init>(Variable.java:25) ~[?:?]
        at net.advancedplugins.bp.impl.actions.objects.variable.Variable.of(Variable.java:74) ~[?:?]
        at io.github.battlepass.cache.QuestCache.parseSection(QuestCache.java:138) ~[?:?]
        at io.github.battlepass.cache.QuestCache.cache(QuestCache.java:93) ~[?:?]
        at io.github.battlepass.BattlePlugin.load(BattlePlugin.java:277) ~[?:?]
        at io.github.battlepass.BattlePlugin.onEnable(BattlePlugin.java:108) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-245]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.tuple.ImmutablePair
        at java.net.URLClassLoader.findClass(URLClassLoader.java:436) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.4.jar:git-Paper-245]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.4.jar:git-Paper-245]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
  ```

### How to reproduce

I've explained it on the describe the bug section, please read it carefully thanks!

### Screenshots / Videos

![image](https://github.com/GC-spigot/battle-pass/assets/58950562/55555060-cb85-4bcc-940e-919e57e1bc31)
**1.14.4 ISSUE WHERE BATTLEPASS IS NOT RUNNING**
Occur in 1.14.4 minecraft version

![image](https://github.com/GC-spigot/battle-pass/assets/58950562/b726e538-f889-4e0d-87a7-57aa17a0ea0b)
**ISSUE WHIT THE ENTITYBREEDQUEST AFTER RELOADING THE PLUGIN /BPA RELOAD**
Occur in 1.12.2 - 1.13.2 minecraft version

**Comment by aXe18** [comment]
@ItzFabb-uwu What if you try first right format in variables ?

**Comment by ItzFabb-uwu** [comment]
> @ItzFabb-uwu What if you try first right format in variables ?

that only works on 1.15.1 as the Wiki said, and it's also does not work.

**Comment by GC-spigot** [comment]
Hi! We'll be dropping support for 1.8 - 1.13 very soon. We have a handful of 1.8 servers using this plugin out of 1500+ servers, and it's clearly now causing issues having support for all versions, cannot keep support for 9+ year old version, it's time to move on.
